// Full world currency list (ISO 4217 active codes) with English and Arabic names for search.
export interface CurrencyInfo {
  code: string;
  en: string;
  ar: string;
  flag: string;
}

export const ALL_CURRENCIES: CurrencyInfo[] = [
  { code: "SAR", en: "Saudi Riyal", ar: "ريال سعودي", flag: "🇸🇦" },
  { code: "USD", en: "US Dollar", ar: "دولار أمريكي", flag: "🇺🇸" },
  { code: "EUR", en: "Euro", ar: "يورو", flag: "🇪🇺" },
  { code: "GBP", en: "British Pound", ar: "جنيه إسترليني", flag: "🇬🇧" },
  { code: "AED", en: "UAE Dirham", ar: "درهم إماراتي", flag: "🇦🇪" },
  { code: "KWD", en: "Kuwaiti Dinar", ar: "دينار كويتي", flag: "🇰🇼" },
  { code: "BHD", en: "Bahraini Dinar", ar: "دينار بحريني", flag: "🇧🇭" },
  { code: "QAR", en: "Qatari Riyal", ar: "ريال قطري", flag: "🇶🇦" },
  { code: "OMR", en: "Omani Rial", ar: "ريال عماني", flag: "🇴🇲" },
  { code: "EGP", en: "Egyptian Pound", ar: "جنيه مصري", flag: "🇪🇬" },
  { code: "JOD", en: "Jordanian Dinar", ar: "دينار أردني", flag: "🇯🇴" },
  { code: "LBP", en: "Lebanese Pound", ar: "ليرة لبنانية", flag: "🇱🇧" },
  { code: "IQD", en: "Iraqi Dinar", ar: "دينار عراقي", flag: "🇮🇶" },
  { code: "SYP", en: "Syrian Pound", ar: "ليرة سورية", flag: "🇸🇾" },
  { code: "YER", en: "Yemeni Rial", ar: "ريال يمني", flag: "🇾🇪" },
  { code: "LYD", en: "Libyan Dinar", ar: "دينار ليبي", flag: "🇱🇾" },
  { code: "TND", en: "Tunisian Dinar", ar: "دينار تونسي", flag: "🇹🇳" },
  { code: "DZD", en: "Algerian Dinar", ar: "دينار جزائري", flag: "🇩🇿" },
  { code: "MAD", en: "Moroccan Dirham", ar: "درهم مغربي", flag: "🇲🇦" },
  { code: "MRU", en: "Mauritanian Ouguiya", ar: "أوقية موريتانية", flag: "🇲🇷" },
  { code: "SDG", en: "Sudanese Pound", ar: "جنيه سوداني", flag: "🇸🇩" },
  { code: "SOS", en: "Somali Shilling", ar: "شلن صومالي", flag: "🇸🇴" },
  { code: "DJF", en: "Djiboutian Franc", ar: "فرنك جيبوتي", flag: "🇩🇯" },
  { code: "KMF", en: "Comorian Franc", ar: "فرنك قمري", flag: "🇰🇲" },
  { code: "TRY", en: "Turkish Lira", ar: "ليرة تركية", flag: "🇹🇷" },
  { code: "IRR", en: "Iranian Rial", ar: "ريال إيراني", flag: "🇮🇷" },
  { code: "PKR", en: "Pakistani Rupee", ar: "روبية باكستانية", flag: "🇵🇰" },
  { code: "INR", en: "Indian Rupee", ar: "روبية هندية", flag: "🇮🇳" },
  { code: "BDT", en: "Bangladeshi Taka", ar: "تاكا بنغلاديشية", flag: "🇧🇩" },
  { code: "LKR", en: "Sri Lankan Rupee", ar: "روبية سريلانكية", flag: "🇱🇰" },
  { code: "NPR", en: "Nepalese Rupee", ar: "روبية نيبالية", flag: "🇳🇵" },
  { code: "AFN", en: "Afghan Afghani", ar: "أفغاني أفغانستاني", flag: "🇦🇫" },
  { code: "MVR", en: "Maldivian Rufiyaa", ar: "روفية مالديفية", flag: "🇲🇻" },
  { code: "IDR", en: "Indonesian Rupiah", ar: "روبية إندونيسية", flag: "🇮🇩" },
  { code: "MYR", en: "Malaysian Ringgit", ar: "رينغيت ماليزي", flag: "🇲🇾" },
  { code: "BND", en: "Brunei Dollar", ar: "دولار بروناي", flag: "🇧🇳" },
  { code: "SGD", en: "Singapore Dollar", ar: "دولار سنغافوري", flag: "🇸🇬" },
  { code: "THB", en: "Thai Baht", ar: "بات تايلندي", flag: "🇹🇭" },
  { code: "PHP", en: "Philippine Peso", ar: "بيزو فلبيني", flag: "🇵🇭" },
  { code: "VND", en: "Vietnamese Dong", ar: "دونغ فيتنامي", flag: "🇻🇳" },
  { code: "KHR", en: "Cambodian Riel", ar: "ريال كمبودي", flag: "🇰🇭" },
  { code: "LAK", en: "Lao Kip", ar: "كيب لاوسي", flag: "🇱🇦" },
  { code: "MMK", en: "Myanmar Kyat", ar: "كيات ميانمار", flag: "🇲🇲" },
  { code: "JPY", en: "Japanese Yen", ar: "ين ياباني", flag: "🇯🇵" },
  { code: "CNY", en: "Chinese Yuan", ar: "يوان صيني", flag: "🇨🇳" },
  { code: "HKD", en: "Hong Kong Dollar", ar: "دولار هونغ كونغ", flag: "🇭🇰" },
  { code: "TWD", en: "Taiwan Dollar", ar: "دولار تايواني", flag: "🇹🇼" },
  { code: "KRW", en: "South Korean Won", ar: "وون كوري جنوبي", flag: "🇰🇷" },
  { code: "MNT", en: "Mongolian Tugrik", ar: "توغروغ منغولي", flag: "🇲🇳" },
  { code: "KZT", en: "Kazakhstani Tenge", ar: "تينغ كازاخستاني", flag: "🇰🇿" },
  { code: "UZS", en: "Uzbekistani Som", ar: "سوم أوزبكستاني", flag: "🇺🇿" },
  { code: "TMT", en: "Turkmenistani Manat", ar: "مانات تركمانستاني", flag: "🇹🇲" },
  { code: "KGS", en: "Kyrgyzstani Som", ar: "سوم قيرغيزستاني", flag: "🇰🇬" },
  { code: "TJS", en: "Tajikistani Somoni", ar: "سوموني طاجيكستاني", flag: "🇹🇯" },
  { code: "AZN", en: "Azerbaijani Manat", ar: "مانات أذربيجاني", flag: "🇦🇿" },
  { code: "GEL", en: "Georgian Lari", ar: "لاري جورجي", flag: "🇬🇪" },
  { code: "AMD", en: "Armenian Dram", ar: "درام أرميني", flag: "🇦🇲" },
  { code: "RUB", en: "Russian Ruble", ar: "روبل روسي", flag: "🇷🇺" },
  { code: "UAH", en: "Ukrainian Hryvnia", ar: "هريفنيا أوكرانية", flag: "🇺🇦" },
  { code: "BYN", en: "Belarusian Ruble", ar: "روبل بيلاروسي", flag: "🇧🇾" },
  { code: "MDL", en: "Moldovan Leu", ar: "ليو مولدوفي", flag: "🇲🇩" },
  { code: "RON", en: "Romanian Leu", ar: "ليو روماني", flag: "🇷🇴" },
  { code: "BGN", en: "Bulgarian Lev", ar: "ليف بلغاري", flag: "🇧🇬" },
  { code: "RSD", en: "Serbian Dinar", ar: "دينار صربي", flag: "🇷🇸" },
  { code: "MKD", en: "Macedonian Denar", ar: "دينار مقدوني", flag: "🇲🇰" },
  { code: "ALL", en: "Albanian Lek", ar: "ليك ألباني", flag: "🇦🇱" },
  { code: "BAM", en: "Bosnian Mark", ar: "مارك بوسني", flag: "🇧🇦" },
  { code: "HUF", en: "Hungarian Forint", ar: "فورنت مجري", flag: "🇭🇺" },
  { code: "CZK", en: "Czech Koruna", ar: "كورونا تشيكية", flag: "🇨🇿" },
  { code: "PLN", en: "Polish Zloty", ar: "زلوتي بولندي", flag: "🇵🇱" },
  { code: "SEK", en: "Swedish Krona", ar: "كرونة سويدية", flag: "🇸🇪" },
  { code: "NOK", en: "Norwegian Krone", ar: "كرونة نرويجية", flag: "🇳🇴" },
  { code: "DKK", en: "Danish Krone", ar: "كرونة دنماركية", flag: "🇩🇰" },
  { code: "ISK", en: "Icelandic Krona", ar: "كرونة آيسلندية", flag: "🇮🇸" },
  { code: "CHF", en: "Swiss Franc", ar: "فرنك سويسري", flag: "🇨🇭" },
  { code: "CAD", en: "Canadian Dollar", ar: "دولار كندي", flag: "🇨🇦" },
  { code: "MXN", en: "Mexican Peso", ar: "بيزو مكسيكي", flag: "🇲🇽" },
  { code: "GTQ", en: "Guatemalan Quetzal", ar: "كتزال غواتيمالي", flag: "🇬🇹" },
  { code: "HNL", en: "Honduran Lempira", ar: "لمبيرا هندوراسية", flag: "🇭🇳" },
  { code: "NIO", en: "Nicaraguan Cordoba", ar: "كوردوبا نيكاراغوية", flag: "🇳🇮" },
  { code: "CRC", en: "Costa Rican Colon", ar: "كولون كوستاريكي", flag: "🇨🇷" },
  { code: "PAB", en: "Panamanian Balboa", ar: "بالبوا بنمية", flag: "🇵🇦" },
  { code: "DOP", en: "Dominican Peso", ar: "بيزو دومينيكاني", flag: "🇩🇴" },
  { code: "JMD", en: "Jamaican Dollar", ar: "دولار جامايكي", flag: "🇯🇲" },
  { code: "TTD", en: "Trinidad Dollar", ar: "دولار ترينيداد", flag: "🇹🇹" },
  { code: "BBD", en: "Barbadian Dollar", ar: "دولار بربادوسي", flag: "🇧🇧" },
  { code: "BSD", en: "Bahamian Dollar", ar: "دولار بهامي", flag: "🇧🇸" },
  { code: "CUP", en: "Cuban Peso", ar: "بيزو كوبي", flag: "🇨🇺" },
  { code: "HTG", en: "Haitian Gourde", ar: "غورد هايتي", flag: "🇭🇹" },
  { code: "BRL", en: "Brazilian Real", ar: "ريال برازيلي", flag: "🇧🇷" },
  { code: "ARS", en: "Argentine Peso", ar: "بيزو أرجنتيني", flag: "🇦🇷" },
  { code: "CLP", en: "Chilean Peso", ar: "بيزو تشيلي", flag: "🇨🇱" },
  { code: "COP", en: "Colombian Peso", ar: "بيزو كولومبي", flag: "🇨🇴" },
  { code: "PEN", en: "Peruvian Sol", ar: "سول بيروفي", flag: "🇵🇪" },
  { code: "UYU", en: "Uruguayan Peso", ar: "بيزو أوروغواي", flag: "🇺🇾" },
  { code: "PYG", en: "Paraguayan Guarani", ar: "غواراني باراغواي", flag: "🇵🇾" },
  { code: "BOB", en: "Bolivian Boliviano", ar: "بوليفيانو بوليفي", flag: "🇧🇴" },
  { code: "VES", en: "Venezuelan Bolivar", ar: "بوليفار فنزويلي", flag: "🇻🇪" },
  { code: "GYD", en: "Guyanese Dollar", ar: "دولار غياني", flag: "🇬🇾" },
  { code: "SRD", en: "Surinamese Dollar", ar: "دولار سورينامي", flag: "🇸🇷" },
  { code: "AUD", en: "Australian Dollar", ar: "دولار أسترالي", flag: "🇦🇺" },
  { code: "NZD", en: "New Zealand Dollar", ar: "دولار نيوزيلندي", flag: "🇳🇿" },
  { code: "FJD", en: "Fijian Dollar", ar: "دولار فيجي", flag: "🇫🇯" },
  { code: "PGK", en: "Papua New Guinean Kina", ar: "كينا بابوا غينيا", flag: "🇵🇬" },
  { code: "ZAR", en: "South African Rand", ar: "راند جنوب أفريقي", flag: "🇿🇦" },
  { code: "NGN", en: "Nigerian Naira", ar: "نيرة نيجيرية", flag: "🇳🇬" },
  { code: "GHS", en: "Ghanaian Cedi", ar: "سيدي غاني", flag: "🇬🇭" },
  { code: "KES", en: "Kenyan Shilling", ar: "شلن كيني", flag: "🇰🇪" },
  { code: "TZS", en: "Tanzanian Shilling", ar: "شلن تنزاني", flag: "🇹🇿" },
  { code: "UGX", en: "Ugandan Shilling", ar: "شلن أوغندي", flag: "🇺🇬" },
  { code: "ETB", en: "Ethiopian Birr", ar: "بير إثيوبي", flag: "🇪🇹" },
  { code: "ERN", en: "Eritrean Nakfa", ar: "ناكفا إريترية", flag: "🇪🇷" },
  { code: "RWF", en: "Rwandan Franc", ar: "فرنك رواندي", flag: "🇷🇼" },
  { code: "BIF", en: "Burundian Franc", ar: "فرنك بوروندي", flag: "🇧🇮" },
  { code: "MWK", en: "Malawian Kwacha", ar: "كواشا مالاوية", flag: "🇲🇼" },
  { code: "ZMW", en: "Zambian Kwacha", ar: "كواشا زامبية", flag: "🇿🇲" },
  { code: "MZN", en: "Mozambican Metical", ar: "متكال موزمبيقي", flag: "🇲🇿" },
  { code: "BWP", en: "Botswanan Pula", ar: "بولا بوتسوانية", flag: "🇧🇼" },
  { code: "NAD", en: "Namibian Dollar", ar: "دولار ناميبي", flag: "🇳🇦" },
  { code: "SZL", en: "Swazi Lilangeni", ar: "ليلانجيني سوازي", flag: "🇸🇿" },
  { code: "LSL", en: "Lesotho Loti", ar: "لوتي ليسوتو", flag: "🇱🇸" },
  { code: "MGA", en: "Malagasy Ariary", ar: "أرياري مدغشقري", flag: "🇲🇬" },
  { code: "MUR", en: "Mauritian Rupee", ar: "روبية موريشيوسية", flag: "🇲🇺" },
  { code: "SCR", en: "Seychellois Rupee", ar: "روبية سيشيلية", flag: "🇸🇨" },
  { code: "XOF", en: "West African CFA Franc", ar: "فرنك غرب أفريقي", flag: "🌍" },
  { code: "XAF", en: "Central African CFA Franc", ar: "فرنك وسط أفريقي", flag: "🌍" },
  { code: "GMD", en: "Gambian Dalasi", ar: "دالاسي غامبي", flag: "🇬🇲" },
  { code: "GNF", en: "Guinean Franc", ar: "فرنك غيني", flag: "🇬🇳" },
  { code: "SLE", en: "Sierra Leonean Leone", ar: "ليون سيراليوني", flag: "🇸🇱" },
  { code: "LRD", en: "Liberian Dollar", ar: "دولار ليبيري", flag: "🇱🇷" },
  { code: "CVE", en: "Cape Verdean Escudo", ar: "إسكودو الرأس الأخضر", flag: "🇨🇻" },
  { code: "STN", en: "Sao Tome Dobra", ar: "دوبرا ساو تومي", flag: "🇸🇹" },
  { code: "AOA", en: "Angolan Kwanza", ar: "كوانزا أنغولية", flag: "🇦🇴" },
  { code: "CDF", en: "Congolese Franc", ar: "فرنك كونغولي", flag: "🇨🇩" },
  { code: "SSP", en: "South Sudanese Pound", ar: "جنيه جنوب السودان", flag: "🇸🇸" },
  { code: "ZWL", en: "Zimbabwean Dollar", ar: "دولار زيمبابوي", flag: "🇿🇼" },
];

/** Search currencies by code, English name, or Arabic name (case/space insensitive). */
export function searchCurrencies(query: string): CurrencyInfo[] {
  const q = query.trim().toLowerCase();
  if (!q) return ALL_CURRENCIES;
  return ALL_CURRENCIES.filter(
    (c) =>
      c.code.toLowerCase().includes(q) ||
      c.en.toLowerCase().includes(q) ||
      c.ar.includes(query.trim()),
  );
}

export function currencyByCode(code: string): CurrencyInfo | undefined {
  return ALL_CURRENCIES.find((c) => c.code === code);
}
